// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sixlyngzimvsacyeqrxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpeGx5bmd6aW12c2FjeWVxcnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODA5NzgsImV4cCI6MjA3Mzc1Njk3OH0.UMO3ARqwDszn6lJlSOEqk1Vw73i-SWDjJOneN7whcFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});